# Generated by Django 2.2.4 on 2019-09-27 08:27

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='google_auth_credentials',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='user',
            name='google_auth_state_key',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
