# Generated by Django 2.2.4 on 2019-09-26 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SlackWorkspace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(max_length=255)),
                ('team_name', models.CharField(max_length=255)),
                ('team_id', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Slack Workspace',
                'verbose_name_plural': 'Slack Workspaces',
            },
        ),
        migrations.CreateModel(
            name='SlackChannel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('channel_id', models.CharField(max_length=255)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channels', to='slack.SlackWorkspace')),
            ],
            options={
                'verbose_name': 'Channel',
                'verbose_name_plural': 'Channels',
                'unique_together': {('workspace', 'channel_id')},
            },
        ),
    ]
